### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [command7/biodiversity#1]
**Overall score 16/16 Great job! Here is the breakdown**

**Criteria1: Presentation / Analysis Document**
**Score 4 (exceeds expectations)**
Comment: 1.Document in PDF format 
2.Overview slide to state the objective of the analysis
3.Data observations slides using matplotlib plots
4. Slide for hypothesis testing and results
5. Recommendation 

**Criteria 2: Code Accuracy**
**Score 4 (exceeds expectations)**
Comment: 1.Accurate Python code for every question in the project for
  a.  pandas for data manipulation
  b. Matplotlib plots
  c.Scipy for Hypothesis testing
2.Accurate calculation of Minimum detectable size, Sample size determination in Foot & Mouth disease analysis	

**Criteria3: Understanding hypothesis testing and interpreting the p value**
**Score 4 (exceeds expectations)**
Comment: 1. State the hypothesis
2. Run hypothesis testing and state the results
3. Based on the results accept/reject the hypothesis
4. Interpret the hypothesis outcome and connect to the objective of the analysis

**Criteria 4:Ability to interpret the Objective & Outcome of the analysis in business context**
**score 4(exceeds expectations)**
1.Objective clearly states the business reason for the analysis
2.Findings are interpreted accurately and are summarized in Recommendation / Conclusion . It addresses the questions raised in  the objective of the analysis

**Comment by command7** [comment]
Thank you
